### ISSUE TITLE
Allow installation with PHPUnit 5.0

### ISSUE THREAD

**Issue by remicollet** [zendframework/zend-test#3]
As the test suite pass with PHPUnit 5.0, I think it would be nice to allow this in composer.json

```
"phpunit/PHPUnit": "~4.0|~5.0",
```

or even

```
"phpunit/PHPUnit": ">=4.0",
```

**Comment by Ocramius** [comment]
`"phpunit/PHPUnit": ">=4.0",` is generally a bad approach, as it doesn't consider future possible BC breaks in major versions.

**Comment by remicollet** [comment]
thanks

**Comment by mesaugat** [comment]
`zendframework/zend-test (2.5.1)` is not allowing PHPUnit upgrade to ~5.0 - When is the next update for zend-test?
