### ISSUE TITLE
assertQueryContentContains

### ISSUE THREAD

**Issue by autowp** [zendframework/zend-test#38]
Sounds like method [assertQueryContentContains](https://github.com/zendframework/zend-test/blob/master/src/PHPUnit/Controller/AbstractHttpControllerTestCase.php#L722) must check for contains substring but equality is checked ([assertEquals is used ](https://github.com/zendframework/zend-test/blob/master/src/PHPUnit/Controller/AbstractHttpControllerTestCase.php#L701)).

It's useless because of whitespaces in HTML.

**Comment by froschdesign** [comment]
Duplicates #30
