### ISSUE TITLE
Multiple dispatch() calls with same Application instance - should it work?

### ISSUE THREAD

**Issue by bitwombat** [zendframework/zend-test#45]
First, importantly, ***thanks guys and girls for the work that went into this module!***

Possibly unconventionally, I'm using it with Behat which means more than one dispatch is required for my one 'Feature' test.

Bottom line means I'm doing something like this:

    public function someBehatStep()
    {
        $this->dispatch('/workers/add', 'POST', $postData);
        $this->assertResponseStatusCode(302);
        $this->assertRedirectTo('/workers/add');
    }

    public function someOtherBehatStep()
    {
        $this->dispatch('/about');
        $this->assertResponseStatusCode(200);
    }

...but the same Application instance survives between them.  It doesn't work right.  The someOtherBehatStep's response status code is always the same as the first step.  I think this is because zend-mvc isn't designed to have Application->run() called multiple times.

To try to fix it myself, I copied the Application init code from zend-test's getApplication method, and calling it between my scenarios above, the 2nd Application->run goes just fine.

Is this expected behavior?

Thanks for the time.

Greg

**Comment by Ocramius** [comment]
Tis is a known limitation. While the application itself can be run multiple
times, any service that isn't stateless will lead to problems. For
instance, the entire view layer doesn't like being reused.

**Comment by bitwombat** [comment]
Alright, thanks.  And my workaround is reasonable?
(not included originally)

    public function resetApplication()
    {
        $appConfig = $this->applicationConfig;
        $this->application = Application::init($appConfig);
        $events = $this->application->getEventManager();
        $this->application->getServiceManager()->get('SendResponseListener')->detach($events);
    }

**Comment by Ocramius** [comment]
Yep, creating a new application and service manager is sufficient

**Comment by bitwombat** [comment]
Sorry @Ocramius, you replied to the email notification from github which didn't have my code snippet.  Here it is below.  I'm not creating a new service manager (simply because I'm doing it the way zend-test does it).  Still OK?

    public function resetApplication()
    {
        $appConfig = $this->applicationConfig;
        $this->application = Application::init($appConfig);
        $events = $this->application->getEventManager();
        $this->application->getServiceManager()->get('SendResponseListener')->detach($events);
    }

**Comment by Ocramius** [comment]
Creating a new application also creates a new servicemanager here ;-)

Make sure you don't keep references to the old service manager.

**Comment by koseduhemak** [comment]
Is it possible to circumvent this limitation?
I monitored that the following code executes the `indexAction` only once (instead of exspected twice).

```
public function testCustom()
    {
        $this->dispatch('/');
        $this->assertActionName('index');
        $this->assertResponseStatusCode(200);

        $this->dispatch('/');
        $this->assertResponseStatusCode(200);
        $this->assertActionName('index');
    }
```
The only way to solve this was to put `$this->reset();` between the two dispatch calls.
If your tests have many dependencies (integration tests) it is very hard to setUp them again and again before each dispatch. Think of an multi-step form which should be tested, where the data of the first step is needed in the second step and so on.

Is it possible to reset only the request specific things in a way that the request is evaluated the second time too?
