### ISSUE TITLE
Wrong Phpunit requirements

### ISSUE THREAD

**Issue by hakre** [zendframework/zend-test#50]
Per composer.json Phpunit below version 6 is acceptable:

        "phpunit/phpunit": "^4.0 || ^5.0 || ^6.0",

But the src is only compatible with `^6.0`.

Refs:

- https://github.com/zendframework/zend-test/blob/master/composer.json#L25

- https://github.com/zendframework/zend-test/blob/master/src/PHPUnit/Controller/AbstractControllerTestCase.php#L12 [Edited: wrong line]

**Comment by remicollet** [comment]
Notice that test suite passes with PHPUnit 5.7.22

But something have change in 5.7.23 which break it
Discover in Fedora QA
=> https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-test?collection=f28

No issue with 6.4.3

/cc @sebastianbergmann as this could be a regression in PHPUnit 5.7.23

**Comment by remicollet** [comment]
>    "phpunit/phpunit": "^4.0 || ^5.0 || ^6.0",

Should probably be ^4.8.36 || ~5.7.21 || ^6.0
Which are the minimal versions which have `PHPUnit\Framework\AssertionFailedError`
