### ISSUE TITLE
unable to install on clean 2.4.x zf

### ISSUE THREAD

**Issue by FLasH3r** [zendframework/zend-test#54]
1. Install cleant zf2 in current empty directory
`composer create-project -sdev --repository-url="https://packages.zendframework.com" zendframework/skeleton-application . 2.4.x`

2. install zend-test
`composer require --dev zendframework/zend-test`

It fails installing dependencies.

> Using version ^3.1 for zendframework/zend-test
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - don't install zendframework/zend-dom 2.6.0|don't install zendframework/zendframework 2.4.11
>     - don't install zendframework/zend-dom 2.6.0|don't install zendframework/zendframework 2.4.12
>     - don't install zendframework/zend-dom 2.6.0|don't install zendframework/zendframework 2.4.13
>     - don't install zendframework/zend-dom 2.6.0|remove zendframework/zendframework 2.4.13
>     - don't install zendframework/zend-dom 2.6.0|don't install zendframework/zendframework 2.4.13
>     - zendframework/zend-test 3.1.0 requires zendframework/zend-dom ^2.6 -> satisfiable by zendframework/zend-dom[2.6.0].
>     - Installation request for zendframework/zend-test ^3.1 -> satisfiable by zendframework/zend-test[3.1.0].
>     - Installation request for zendframework/zendframework ~2.4.11 -> satisfiable by zendframework/zendframework[2.4.11, 2.4.12, 2.4.13].

Not sure if this is a composer error or not.

**Comment by Ocramius** [comment]
@FLasH3r not an error: you will have to install an older version of `zend-test`. Composer picks the latest stable version of `zend-test` as minimum constraint, and that obviously fails when combined with a very old component.

**Comment by froschdesign** [comment]
@FLasH3r 
You can use simplify the install command:

```bash
composer create-project zendframework/skeleton-application path/to/install 2.4.*
```

**Comment by FLasH3r** [comment]
@francisdaigle - that's what I did in line 1. but I'm having trouble finding the correct version to install zend-test - how do I know which version fits zend 2.4.x ?

**Comment by froschdesign** [comment]
@FLasH3r 
> that's what I did in line 1.

Not really. I do not need the extra parameters `-sdev` and `--repository-url`.

> how do I know which version fits zend 2.4.x ?

If composer detects conflicts or other problems, than you can add also the version number:

```bash
composer require --dev zendframework/zend-test:2.4.*
```

See: https://getcomposer.org/doc/03-cli.md#require

**Comment by FLasH3r** [comment]
@francisdaigle I know `-sdev` is not required -  it's from the docs 

https://framework.zend.com/manual/2.4/en/ref/installation.html
