### ISSUE TITLE
Memory Leak in Application

### ISSUE THREAD

**Issue by wodka** [zendframework/zend-test#69]
I just ran into an out of memory error and tried to figure out why it is happening.  The moment the Application is used the memory goes up and never down.

### Code to reproduce the issue

Depending on how much memory you want it to consume you can increase the array size of the data provider.

```php
<?php

use Zend\Test\PHPUnit\Controller\AbstractControllerTestCase;

class UselessTest extends AbstractControllerTestCase
{
	public function setUp()
	{
		parent::setUp();

		$this->setApplicationConfig(
			[
				'modules'                 => [
					'Zend\\Router',
				],
				'module_listener_options' => [],
			]
		);
	}

	/**
	 * @dataProvider dataProvider
	 */
	public function testNull($variable)
	{
		$this->getApplication();

		echo memory_get_usage(true) / 1000 / 1024 . PHP_EOL;

		$this->assertNull($variable);
	}

	public static function dataProvider()
	{
		return array_fill(0, 1000, [ null ]);
	}
}

```

### Expected results

I would expect the memory to stay low - ie similar to not using the Application (~6Mb for all tests)

### Actual results

Memory usage keeps growing

![image](https://user-images.githubusercontent.com/385731/42621211-7a2aedcc-85bd-11e8-854a-18be50007cef.png)

**Comment by porebskk** [comment]
Experiencing the same for larger apps with lots of integration tests (zf3 + doctrine2). The memory piles up for every single test that was executed. This affects all test that inherit from `AbstractHttpControllerTestCase`.

**Comment by snapshotpl** [comment]
Same issue. This is due to the global state in ZF3.

**Comment by porebskk** [comment]
@snapshotpl could you point me to where the global state is hold in zf3? Maybe it is possible to clear or reset the state in order to overcome this memory collection madness.

**Comment by ezimuel** [comment]
@porebskk, @snapshotpl, @wodka  I'm looking into this issue.
