### ISSUE TITLE
I guess the BC problem occurred after update

### ISSUE THREAD

**Issue by svycka** [zendframework/zend-test#9]
composer log:

```
$ composer install --no-dev --dry-run
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpunit/php-code-coverage 3.0.2 -> satisfiable by phpunit/php-code-coverage[3.0.2].
    - phpunit/php-code-coverage 3.0.2 requires php >=5.6 -> your PHP version (5.5.9-1ubuntu4.11) or value of "config.platform.php" in composer.json does not satisfy that requirement.
  Problem 2
    - Installation request for phpunit/phpunit 5.1.3 -> satisfiable by phpunit/phpunit[5.1.3].
    - phpunit/phpunit 5.1.3 requires php >=5.6 -> your PHP version (5.5.9-1ubuntu4.11) or value of "config.platform.php" in composer.json does not satisfy that requirement.
  Problem 3
    - Installation request for phpunit/phpunit-mock-objects 3.0.6 -> satisfiable by phpunit/phpunit-mock-objects[3.0.6].
    - phpunit/phpunit-mock-objects 3.0.6 requires php >=5.6 -> your PHP version (5.5.9-1ubuntu4.11) or value of "config.platform.php" in composer.json does not satisfy that requirement.
  Problem 4
    - Installation request for sebastian/resource-operations 1.0.0 -> satisfiable by sebastian/resource-operations[1.0.0].
    - sebastian/resource-operations 1.0.0 requires php >=5.6.0 -> your PHP version (5.5.9-1ubuntu4.11) or value of "config.platform.php" in composer.json does not satisfy that requirement.
  Problem 5
    - phpunit/phpunit 5.1.3 requires php >=5.6 -> your PHP version (5.5.9-1ubuntu4.11) or value of "config.platform.php" in composer.json does not satisfy that requirement.
    - zendframework/zend-test 2.5.2 requires phpunit/phpunit ~4.0|~5.0 -> satisfiable by phpunit/phpunit[5.1.3].
    - Installation request for zendframework/zend-test 2.5.2 -> satisfiable by zendframework/zend-test[2.5.2].
```

this was strange to me because i don't have phpunit/phpunit in my composer.json but well I have `"zendframework/zendframework": "~2.5"` with forces phpunit installation. before https://github.com/zendframework/zend-test/commit/4729662dd8f514f4c35d24c3a95dd2057a6ed4d0 I didn't had any problems for me this is almost BC.

ok, there is also a bit of my fault. I have php5.6 on my dev mashine where I generated composer.lock but some my production servers has 5.5 so they does not meet requirements from composer.lock

Maybe this is not big BC but well I did not expected that composer with --no-dev could stop my deployment because of phpunit. I guess not only me can run into this problem no?

Related: https://github.com/zendframework/zf2/issues/7574

**Comment by Ocramius** [comment]
@svycka this seems correct: zend-test indeed requires PHPUnit `~4.0|~5.0`, although it is indeed annoying that the framework requires it by default.

One fix that I can see is that zendframework could move zend-test into a dev dependency for 3.0 (would be a BC break).

I suggest that you do two things:
- provide a copy of your `composer.json` and current PHP version/extensions installed
- see the dependency graph via https://github.com/clue/graph-composer (maybe something else in your dependencies is causing clashes)

Given the non-restrictive dependencies, this may also end up being a composer bug...

**Comment by svycka** [comment]
@Ocramius the problem is that I generate `composer.lock` with php5.6 but my production is php5.5 and when I generate it, it chooses phpunit5.\* when php5.5 can only be used with phpunit4.*
before https://github.com/zendframework/zend-test/commit/4729662dd8f514f4c35d24c3a95dd2057a6ed4d0 only 4.0 version of phpunit was  supported so I didn't had any problems.
For a fix I can add phpunit4.0 to my composer dev requirements or stop using zendframework meta package.

**Comment by Ocramius** [comment]
> @Ocramius the problem is that I generate `composer.lock` with php5.6 but my production is php5.5 

DON'T!

The `composer.lock` must be tailored to your deployment environment: of course you will get problems from that!

**Comment by Ocramius** [comment]
While the removal of `zend-test` from the zf2 dependencies still stands, I don't think it is a big issue for 3.x (as people will migrate to depending on single components anyway), whereas the BC break in the meta-component would be more serious.

That said, this issue is invalid as per https://github.com/zendframework/zend-test/issues/9#issuecomment-170519101, which evidences erroneous composer usage.
